remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: メトロファインダー
description: 地下鉄の路線ロゴを検出して時刻表を表示するアプリ
show_downloads: false

# テーマのカスタマイズ
colors:
  header: "#00BBE7"  # アプリのメインカラー
  gradient_top: "#00BBE7"
  gradient_bottom: "#03A9D3" 
